# Generated by Django 5.1 on 2024-09-16 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_first_name', models.CharField(max_length=50)),
                ('arabic_last_name', models.CharField(max_length=50)),
                ('latin_fullname', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.branche')),
            ],
        ),
    ]
