# Generated by Django 5.1 on 2024-09-16 20:16

import Registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='birth_certificat',
            field=models.FileField(null=True, upload_to='Birth_cer/', validators=[Registrations.models.validate_file_size, Registrations.models.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='registrations',
            name='blood_type',
            field=models.FileField(null=True, upload_to='blood_type/', validators=[Registrations.models.validate_file_size, Registrations.models.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='registrations',
            name='white_pic',
            field=models.ImageField(null=True, upload_to='white_image/'),
        ),
    ]
