# Generated by Django 5.1 on 2024-09-22 21:55

import Registrations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0002_registrations_birth_certificat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='registrations',
            name='medical_certificat',
            field=models.FileField(null=True, upload_to='medical_cer/', validators=[Registrations.models.validate_file_size, Registrations.models.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='registrations',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AchievementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achievements/')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Registrations.achievement')),
            ],
        ),
    ]
