# Generated by Django 5.1 on 2024-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0003_achievement_registrations_medical_certificat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
