# Generated by Django 5.1 on 2024-09-28 15:14

import Registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0004_registrations_email_registrations_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='birth_certificat',
            field=models.FileField(blank=True, null=True, upload_to='Birth_cer/', validators=[Registrations.models.validate_file_size, Registrations.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='blood_type',
            field=models.FileField(blank=True, null=True, upload_to='blood_type/', validators=[Registrations.models.validate_file_size, Registrations.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='medical_certificat',
            field=models.FileField(blank=True, null=True, upload_to='medical_cer/', validators=[Registrations.models.validate_file_size, Registrations.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='white_pic',
            field=models.ImageField(blank=True, null=True, upload_to='white_image/'),
        ),
    ]
