# Generated by Django 5.1 on 2024-09-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0005_registrations_category_registrations_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='category',
            field=models.CharField(blank=True, choices=[('Poussin', 'Poussin: 9-10 years'), ('Benjamin', 'Benjamin: 11-12 years'), ('Minime', 'Minime: 13-14 years'), ('Cadet', 'Cadet: 15-16 years'), ('Junior', 'Junior: 17-18 years'), ('Senior', 'Senior: 19-34 years')], max_length=50, null=True),
        ),
    ]
